baseline: Your blogging assistant.
output:
  formats:
    - name: netlify_redirects
      mediatype: text/plain
      extension: ""
theme: hyde
keywords: Cecil, Static Site Generator, SSG
author: Arnaud Ligny
netlify:
  cms:
    path: admin
    version: latest
  identity:
    version: v1
title: The Butler
description: A ready to use static blog, powered by Cecil.
baseurl: /
canonicalurl: true
tags:
  - test
  - pouet
date:
  format: j F Y
  timezone: Europe/Paris
postprocess:
  enabled: true
virtualpages:
  - path: admin
    title: Content Manager (Netlify CMS)
    layout: admin/index
    output: html
  - path: _redirects
    output: netlify_redirects
