title: Starter blog
baseline: Your blog's butler.
description: 'A ready to use static blog, powered by Cecil and Hyde!'
baseurl: /
canonicalurl: true
theme: hyde
date:
  format: j F Y
  timezone: Europe/Paris
pagination:
  max: 5
  path: page
output:
  formats:
    netlify_redirects:
      extension: test
      mediatype: text/plain
virtualpages:
  _redirects:
    output: netlify_redirects
  admin:
    layout: admin/index
    title: Content Manager (Netlify CMS)
    output: html
netlify:
  cms:
    path: admin
    version: latest
  identity:
    version: v1
