title: Starter blog
baseline: Your blog's butler.
baseurl: /
canonicalurl: true
description: A ready to use static blog powered by Cecil and Hyde...
pagination:
  max: 5
  path: page
date:
  format: j F Y
  timezone: Europe/Paris
theme: hyde
netlify:
  cms:
    path: admin
    version: latest
  identity:
    version: v1
