site:
  title: 'Cecil'
  baseline: "Your blog's butler."
  baseurl: '/'
  canonicalurl: true
  description: "Starter blog, with Netlify CMS."
  paginate:
    max: 5
    path: 'page'
  date:
    format: 'j F Y'
    timezone: 'Europe/Paris'
  netlify:
    cms:
      path: 'admin'
      version: 'latest'
    identity:
      version: 'v1'
  output:
    formats:
      netlify_redirects:
        mediatype: 'text/plain'
        extension: ''
  virtualpages:
    admin:
      layout: admin/index
      title: 'Content Manager (Netlify CMS)'
    netlify:
      redirect: https://www.netlify.com
    _redirects:
      output: netlify_redirects
theme: 'hyde'
