name: Build and deploy
on:
  push:
    branches:
      - cecil
env:
  INTL: false
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: php:7.2-cli-alpine
    steps:
    - name: Install PHP extensions
      if: ${{INTL}}
      run: |
        apk update
        apk add --no-cache gettext-dev icu-dev
        docker-php-ext-install -j$(nproc) gettext
        docker-php-ext-install -j$(nproc) intl
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Install theme(s)
      run: |
        curl -sS https://getcomposer.org/installer | php
        composer.phar install --prefer-dist --no-dev --no-progress --no-interaction
    - name: Build site with Cecil
      env:
        CECIL_VERSION: '5.14.4'
        CECIL_BASEURL: '/'
      run: |
        if [[ -z "$CECIL_VERSION" ]]; then
          echo "### Downloading Cecil"
          curl -sSOL https://cecil.app/cecil.phar
        else
          echo "### Downloading Cecil $CECIL_VERSION"
          curl -sSOL https://cecil.app/download/$CECIL_VERSION/cecil.phar
        fi
        echo "### Building Cecil static site"
        php cecil.phar build -v
        echo "### Cecil Action done"
    - name: Deploy site to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@2.0.1
      env:
        EMAIL: arnaud@ligny.org
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: _site
